project:
  type: website

website:
  title: "Hridika Shah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
       text: About
      - href: example-analysis.qmd
        text: Example Analysis

format:
  html:
    theme: united
    css: styles.css
    toc: true



