---
title: "About"
---

I am Hridika Shah, a health policy researcher in training, hoping to increase the role of evidence in addiction-related policies in the United States. My past work at harm reduction centers and as a qualitative interviewer has illuminated the patchwork of U.S. health care and social support policies that I hope to address through my work. 

Overarchingly, I am passionate about investigating: what is the blueprint of a successful, comprehensive model of services for people who use drugs? I hope my work can demonstrate how to leverage policy to equitably expand access to substance use disorder treatment and serve the needs of policymakers, practitioners, and advocates in the substance use and mental health fields. In my future work, I would love to collaborate with and amplify voices of people with lived experience.

## EDUCATION

**Johns Hopkins Bloomberg School of Public Health, Baltimore, MD**	
Doctor of Philosophy in Health Policy | Expected 2028

**Johns Hopkins Bloomberg School of Public Health, Baltimore, MD**	
Master of Science in Public Health in Health Policy | 2024 	
Certificate in Public Health Economics | 2024

**Johns Hopkins University, Baltimore, MD**	 	
Bachelor of Arts in Public Health and Economics | 2022

## ACADEMIC/PROFESSIONAL EXPERIENCE 
	
Senior Research Program Coordinator | Johns Hopkins Bloomberg School of Public Health	
June 2023-June 2024 | Baltimore, MD

- Liaised with partners to coordinate Bloomberg Overdose Prevention Initiative projects in Michigan.
- Contributed to the authoring, review, and revision of manuscripts, reports, and presentations.
- Collaboratively developed research plans and study instruments for submission to the IRB.
- Recruited and conducted qualitative interviews for a study evaluating the impact of COVID-19 housing 
policies among people who use drugs.

Teaching Assistant | Johns Hopkins Bloomberg School of Public Health	
August 2023-May 2024 | Baltimore, MD

- Economic Evaluation I (Term 1), Research and Evaluation Methods for Health Policy (Term 3), 
Housing Insecurity and Health (Term 4)
- Assisted in grading assignments and providing constructive feedback to graduate students.
- Managed student correspondence and other non-instructional duties to support faculty.

Undergraduate & Graduate Intern, Bloomberg Overdose Prevention Initiative	
January 2020-May 2023 | Baltimore, MD

- Conducted literature reviews and composed policy memos on telemedicine regulations, 
opioid settlement funds, and medications for opioid use disorder prescribing laws.
- Prepared, cleaned, and visualized quantitative survey data on opioid use disorder in New Jersey jails 
and presented analyses to state health officials.
- Provide mentorship to current undergraduate project interns.

Graduate Research Assistant in Department of Mental Health, Johns Hopkins Bloomberg School of Public Health	 
June 2022-May 2023 | Baltimore, MD

- Conceptualized and performed legal mapping of state SNAP policies between 2000 and 2021.
- Formulated and produced literature reviews of peer-reviewed and grey literature on the 
impacts of state SNAP policies on participant health outcomes.

Harm Reduction Policy Intern, Atlanta Harm Reduction Coalition	
May 2022-August 2022 | Atlanta, GA

- Surveyed clients for community need assessment and assisted with weekly community outreach.
- Assisted in writing grant proposals, conducting analyses, and developing reports. 
- Investigated data and authored pamphlets on drug paraphernalia and Good Samaritan laws.

Health & Benefits Consulting Intern, Mercer, Marsh, & McLennan Companies	
June 2021-December 2021 | Atlanta, GA

- Analyzed health care claims, utilization data, and cost projections for health insurance plans.
- Supported senior consultants in reviewing client needs strategies for health and benefits packages.

## PUBLICATIONS AND PRESENTATIONS

### Peer-reviewed publications

1.	Shah H. Bandara A, McCourt AD. Laws Limiting Access to SNAP Benefits for People with Felony Drug Convictions: A Policy Mapping Study. Am J Public Health. In Press.

2.	Heidari O, Shah H, Bhagwat A, Ahmad NJ, Whaley S, Sherman SG, Morris M, Saloner B. Changes in opioid treatment programs and harm reduction provider services during the COVID-19 pandemic: Findings from 10 states. Psychol Serv. 2023 Oct 12. doi: 10.1037/ser0000805. Epub ahead of print.

3.	Sugarman OK, Shah H, Whaley S, McCourt A, Saloner B, Bandara S. Examining policy responses to xylazine in the drug supply: A legal policy content analysis. Int. J Drug Policy. 2024 July 1;129:104472. doi: 10.1016/j.drugpo.2024.104472.
 
4.	Song M, Desai IK, Meyer A, Shah H, Saloner B, Sherman SG, Allen ST, Tomko C, Schneider KE, Krawczyk N, Whaley S, Churchill J, Harris SJ. Exploring trauma and wellbeing of people who use drugs after witnessing overdose: A qualitative study. Int J Drug Policy. 2023 Oct 25;122:104239. doi: 10.1016/j.drugpo.2023.104239.

5.	Krawczyk N, Bandara S, Merritt S, Shah H, Duncan A, McEntee B, Schiff M, Ahmad NJ, Whaley S, Latimore A, Saloner B. Jail-based treatment for opioid use disorder in the era of bail reform: a qualitative study of barriers and facilitators to implementation of a state-wide medication treatment initiative. Addict Sci Clin Pract. 2022 Jun 2;17(1):30. doi: 10.1186/s13722-022-00313-6.

6.	Krawczyk N, Allen ST, Schneider KE, Solomon K, Shah H, Morris M, Harris SJ, Sherman SG, Saloner B. Intersecting substance use treatment and harm reduction services: exploring the characteristics and service needs of a community-based sample of people who use drugs. Harm Reduct J. 2022 Aug 24;19(1):95. doi: 10.1186/s12954-022-00676-8.

7.	Feder KA, Harris SJ, Byrne L, Miller SM, Sodder S, Berman V, Livingston A, Edwards J, Hartman S, Sugarman OK, Shah H, Xu J, Raikes J, Gattine S, Saloner B. Attitudes and beliefs about Vermont's 2021 buprenorphine decriminalization law among residents who use illicit opioids. Drug Alcohol Depend. 2023 Sep 1;250:110879. doi: 10.1016/j.drugalcdep.2023.110879. 

### Non-peer reviewed publications

1.	Sugarman OK, Shah H, Whaley S. Tracking “Tranq” Laws: The state of policy responses to the growing xylazine crisis. Opioid Principles. Published August 30, 2023. Available at: https://opioidprinciples.jhsph.edu/tracking-tranq-laws-the-state-of-policy-responses-to-the-growing-xylazine-crisis/. [Working paper].

2.	Larweh H and Shah H. Pharmacist and Prescriber Perceptions on Buprenorphine Prescribing and Dispensing. Published May 22, 2024. Available at: https://opioidprinciples.jhsph.edu/pharmacist-and-prescriber-perceptions-on-buprenorphine-prescribing-and-dispensing/.

3.	Harris SJ, Meyer A, Whaley S, Bhagwat A, Shah H, Sherman SG, Allen ST, Saloner, B. In Their Own Words: Experiences of People Who Use Drugs During the COVID-19 Pandemic. Published March 17, 2022. Available at: https://americanhealth.jhu.edu/news/new-report-shares-perspectives-people-who-use-drugs-during-pandemic.

### Presentations

1.	Shah H, Whaley S, Ahmad NJ, Patel E, Kim E, Bhagwat A, Maniates H, Merritt S, Bandara S, Krawczyk N, Heidari O. Interventions for Co-use of Opioids and Methamphetamine: A Scoping Review. NYU Langone Health Polysubstance Use Symposium. Oral Presentation (October 2022).

2.	Shah H. Bandara A, McCourt AD. Laws Limiting Access to SNAP Benefits for People with Felony Drug Convictions: A Policy Mapping Study. American Public Health Association (APHA) Annual Meeting. Roundtable Presentation (November 2023).

3.	Harris SJ, Meyer A, Shah H, Song M, Desai IK, Krawczyk N, Allen ST, Sherman SG, Saloner B. Narratives of Engaging in Emergency Services, Drug Treatment, and Harm Reduction Services following Nonfatal Overdose in the COVID-19 Pandemic Across States. Academy Health Annual Research Meeting. (June 2023).

4.	Harris SJ, Meyer A, Song M, Desai IK, Shah H, Sherman SG, Saloner B. Utilization of harm reduction services following nonfatal overdose events during the COVID-19 pandemic in the United States: Results from a cohort study of overdose survivors. International AIDS Conference. (July 2022).

### Works in progress

1.	Shah H, Meyer A, Song M, Desai IK, Whaley S, Heidari O, Allen ST, Krawczyk N, Sherman SG, Saloner B, Harris SJ. “That’s the recipe for me, I relapsed”: A Qualitative Study on the Impact of COVID-19 on Overdose Mortality from the Perspective of Survivors and Witnesses of Drug Overdose. [Under Review].

2.	O Heidari, K Feder, H Shah, I Desai, E Yeung, J Xu. Evaluation of Emergency Medical System and Social Work Co-Response to Opioid Overdoses. [Under Review]. 

3.	Gibbons JB, Sugarman OK, Byrne L, Harris SJ, Shah H, Husley E, Rwan J, Rosner EM, Pantaleo A, Bergquist E, Saloner B. Michigan’s Naloxone Leave Behind Program: Perceptions of Emergency Medical Services Personnel. [Under Review].

## SKILLS 

Statistical Programs & Qualitative Software: R, Stata, ATLAS.ti, Dedoose
Survey & Data Management: Research Electronic Data Capture (REDCap), Qualtrics